((magit-branch nil)
 (magit-commit nil)
 (magit-dispatch nil)
 (magit-file-dispatch nil)
 (magit-gitignore nil)
 (magit-merge nil)
 (magit-pull nil)
 (magit-push nil)
 (magit-rebase
  ("--autostash"))
 (magit-stash nil))
