;;; haskell-snippets-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from haskell-snippets.el

(autoload 'haskell-snippets-initialize "haskell-snippets")
(eval-after-load 'yasnippet '(haskell-snippets-initialize))

;;; End of scraped data

(provide 'haskell-snippets-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; haskell-snippets-autoloads.el ends here
